### ISSUE TITLE
looks great, first issues

### ISSUE THREAD

**Issue by jir322** [ChinzoD/vendor-upload#1]
Create a  My Info page 

support the following fields

company name (supplied at login) 
address (text box) 
telephone number   text 40 
toll free number text 40 
fax number  text 40 
website text 80
sales email  text 40

non-editable:  Member Since 2018 (thus date field) 

estimated catalog update frequency:  popup.  choice of  weekly, monthly, quarterly, annually.

non-editable:  date of last successful update    (thus date  yyyy-mm-dd or similar in database)

logo:   (select)  allows them to upload their logo .   Whatever size, we will resize to fit our system
We request 200 x 300  (2: 3 ratio)

editable:  Company description
text box  10 lines, 80 columns, where they can write anything they like about their company.

**Comment by ChinzoD** [comment]
Completed

**Comment by jir322** [comment]
right now the icon is only exposed on the company info page of the user who
logs in. Can we expose it also on the admin pages please?

If defined, can we also show it on all pages of a logged in user, including
the welcome splash screen.



John Irwin
UCSF Pharmaceutical Chemistry
http://irwinlab.compbio.ucsf.edu

**Comment by ChinzoD** [comment]
completed
